name: 数据库备份

on:
  watch:
    types: started
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 4,16 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 下载文件
      run: |
        sudo wget ${{ secrets.URL }}
      
    - name: 更新系统
      run: |
       sudo apt-get update
       sudo apt-get install mailutils -y
    - name: 发送邮件
      run: |
        echo '${{ secrets.ZIP }}'>zip.txt
        echo 'db backup file.' | mail -s "backup file" dcb@qq.com --attach=db.db --attach=zip.txt
        curl -fsSL git.io/file-transfer | sh
        tar zcvf - db.db | ${{ secrets.PASSWORD }} -out db.tar.gz
        ./transfer cow --block 2621440 -s -p 64 --no-progress ./db.tar.gz 2>&1 | tee cowtransfer.log

        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"

      
