name: 数据库备份

on:
  watch:
    types: started
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 4,16 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 下载文件
      run: |
        sudo wget ${{ secrets.URL }}
      
    - name: 更新系统
      run: |
       sudo apt-get update
       sudo apt-get install mailutils -y
    - name: 发送邮件
      run: |
        echo '备份数据库文件' | sudo mail -s "数据库备份!" -A ./db.db dcb@qq.com
